export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH_MUST_BE_FROM_2_TO_100: 'Name must be between 2 and 100 characters long',
  NAME_MUST_BE_STRING: 'Name must be a string',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_OR_PASSWORD_IS_NOT_CORRECT: 'Email or password is not correct',
  INVALID_EMAIL: 'Invalid email format',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  PASSWORD_TOO_WEAK: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Password must be between 6 and 50 characters long',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Confirm password must be between 6 and 50 characters long',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_MUST_BE_STRING: 'Date of birth must be a string',
  DATE_OF_BIRTH_MUST_BE_IN_THE_PAST: 'Date of birth must be in the past',
  DATE_MUST_BE_ISO8601: 'Date must be in ISO 8601 format',
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_FAILED: 'Login failed',
  USER_BANNED: 'User account is banned',
  REGISTER_SUCCESS: 'Registration successful',
  REGISTER_FAILED: 'Registration failed',
  CHECK_EMAIL_FAILED: 'Check email exists failed',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: 'Used refresh token or not exists',
  LOGOUT_SUCCESS: 'Logout successful',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_VERIFY_SUCCESS: 'Email verification successful',
  INVALID_EMAIL_VERIFY_TOKEN: 'Invalid email verify token',
  RESEND_EMAIL_VERIFY_SUCCESS: 'Resend email verification successful',
  EMAIL_NOT_FOUND: 'Email not found',
  FORGOT_PASSWORD_EMAIL_SENT:
    'If that email address is in our database, we will send you an email to reset your password',
  RESET_PASSWORD_TOKEN_IS_REQUIRED: 'Reset password token is required',
  INVALID_RESET_PASSWORD_TOKEN: 'Invalid reset password token',
  RESET_PASSWORD_SUCCESS: 'Reset password successful',
  RESET_PASSWORD_FAILED: 'Reset password failed',
  INVALID_FORGOT_PASSWORD_TOKEN: 'Invalid forgot password token',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Verify forgot password token successful',
  GET_PROFILE_SUCCESS: 'Get profile successful',
  USER_NOT_VERIFIED: 'User not verified. Please verify your email first',
  UPDATE_PROFILE_SUCCESS: 'Update profile successful',
  BIO_LENGTH_MUST_BE_UP_TO_500: 'Bio must be up to 500 characters long',
  BIO_MUST_BE_STRING: 'Bio must be a string',
  LOCATION_LENGTH_MUST_BE_UP_TO_100: 'Location must be up to 100 characters long',
  LOCATION_MUST_BE_STRING: 'Location must be a string',
  WEBSITE_MUST_BE_A_VALID_URL: 'Website must be a valid URL',
  BIO_MUST_BE_AT_MOST_500_CHARACTERS_LONG: 'Bio must be at most 500 characters long',
  LOCATION_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Location must be at most 400 characters long',
  WEBSITE_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Website must be at most 400 characters long',
  USERNAME_MUST_BE_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_FROM_2_TO_30: 'Username must be between 2 and 30 characters long',
  IMAGE_URL_MUST_BE_STRING: 'Image URL must be a string',
  IMAGE_URL_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Image URL must be at most 400 characters long',
  GET_ME_SUCCESS: 'Get me successful',
  FOLLOW_USER_SUCCESS: 'Follow user successful',
  FOLLOW_USER_ID_MUST_BE_STRING: 'follow_user_id must be a string',
  FOLLOW_USER_ID_IS_REQUIRED: 'follow_user_id is required',
  CANNOT_FOLLOW_YOURSELF: 'You cannot follow yourself',
  ALREADY_FOLLOWING_THIS_USER: 'You are already following this user',
  FOLLOW_USER_ID_MUST_BE_A_VALID_ID: 'follow_user_id must be a valid ID',
  ALREADY_FOLLOWED_USER: 'You have already followed this user',
  INVALID_USER_ID: 'Invalid user ID',
  ALREADY_UNFOLLOWED_USER: 'You have already unfollowed this user',
  UNFOLLOW_USER_SUCCESS: 'Unfollow user successful',
  CANNOT_FOLLOW_OR_UNFOLLOW_YOURSELF: 'You cannot follow or unfollow yourself',
  USERNAME_MUST_BE_4_15_CHARACTERS_LONG_AND_CAN_ONLY_CONTAIN_LETTERS_NUMBERS_AND_UNDERSCORES:
    'Username must be 4-15 characters long and can only contain letters, numbers, and underscores',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  CURRENT_PASSWORD_IS_INCORRECT: 'Current password is incorrect',
  OLD_PASSWORD_NOT_MATCH: 'Old password is incorrect',
  CHANGE_PASSWORD_SUCCESS: 'Change password successful',
  CONFIRM_PASSWORD_DO_NOT_MATCH: 'Confirm password do not match',
  GMAIL_NOT_VERIFIED: 'Gmail account is not verified',
  UPLOAD_IMAGE_SUCCESS: 'Image uploaded successfully',
  FILE_IS_NOT_VALID: 'File is not valid',
  FILE_IS_EMPTY: 'File is empty',
  UPLOAD_VIDEO_SUCCESS: 'Video uploaded successfully',
  REQUIRE_RANGE_HEADER: 'Requires Range header',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successful',
  PHONE_NUMBER_MUST_BE_STRING: 'Phone number must be a string',
  PHONE_NUMBER_LENGTH_INVALID: 'Phone number must be between 10 and 15 characters',
  GENDER_INVALID: 'Gender must be 0 or 1',
  ADDRESS_MUST_BE_OBJECT: 'Address must be an object',
  ADDRESS_INVALID: 'Address is invalid',
  WARD_INVALID: 'Ward is invalid',
  CITY_INVALID: 'City is invalid',
  IS_DEFAULT_INVALID: 'Is default must be boolean',
  LISENSE_NUMBER_MUST_BE_STRING: 'License number must be a string',
  LISENSE_NUMBER_LENGTH_INVALID: 'License number must be between 1 and 50 characters',
  UNAUTHENTICATED: 'Unauthenticated',
  GET_WISHLIST_SUCCESS: 'Get wishlist successfully',
  ADD_TO_WISHLIST_SUCCESS: 'Added to wishlist successfully',
  REMOVE_FROM_WISHLIST_SUCCESS: 'Removed from wishlist successfully',
  ADMIN_REQUIRED: 'Admin role required',
  PHARMACIST_REQUIRED: 'Pharmacist role required',
  ADMIN_OR_PHARMACIST_REQUIRED: 'Admin or Pharmacist role required'
} as const

export const ADDRESS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  MISSING_REQUIRED_FIELDS: 'Missing required fields',
  MAX_ADDRESSES_REACHED: 'Maximum 5 addresses allowed',
  ADDRESS_NOT_FOUND: 'Address not found',
  ADD_ADDRESS_SUCCESS: 'Address added successfully',
  UPDATE_ADDRESS_SUCCESS: 'Address updated successfully',
  DELETE_ADDRESS_SUCCESS: 'Address deleted successfully',
  SET_DEFAULT_ADDRESS_SUCCESS: 'Default address set successfully',
  GET_ADDRESSES_SUCCESS: 'Get addresses successfully'
} as const

export const CATEGORIES_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_ALREADY_EXISTS: 'Category with this name or slug already exists',
  PARENT_CATEGORY_NOT_FOUND: 'Parent category not found',
  CANNOT_DELETE_CATEGORY_WITH_CHILDREN: 'Cannot delete category that has child categories',
  CANNOT_DELETE_CATEGORY_WITH_PRODUCTS: 'Cannot delete category that contains products',
  INVALID_PARENT_CATEGORY: 'Invalid parent category - would create circular reference',
  MAX_LEVEL_EXCEEDED: 'Maximum category level exceeded (max 3 levels)',

  // Field validation messages
  NAME_IS_REQUIRED: 'Category name is required',
  NAME_MUST_BE_STRING: 'Category name must be a string',
  NAME_LENGTH_INVALID: 'Category name must be between 1 and 100 characters',
  SLUG_IS_REQUIRED: 'Category slug is required',
  SLUG_MUST_BE_STRING: 'Category slug must be a string',
  SLUG_FORMAT_INVALID: 'Category slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Category slug must be between 1 and 100 characters',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_INVALID: 'Description must be up to 500 characters',
  PARENT_ID_MUST_BE_VALID_OBJECT_ID: 'Parent ID must be a valid ObjectId',
  CATEGORY_ID_INVALID: 'Category ID must be a valid ObjectId',
  ICON_MUST_BE_STRING: 'Icon must be a string',
  ICON_URL_INVALID: 'Icon URL must be a valid URL',
  THUMBNAIL_IMAGE_MUST_BE_STRING: 'Thumbnail image must be a string',
  THUMBNAIL_URL_INVALID: 'Thumbnail image URL must be a valid URL',
  SORT_ORDER_INVALID: 'Sort order must be a non-negative number',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  LEVEL_INVALID: 'Level must be between 0 and 10',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',

  // Success messages
  CREATE_CATEGORY_SUCCESS: 'Category created successfully',
  UPDATE_CATEGORY_SUCCESS: 'Category updated successfully',
  DELETE_CATEGORY_SUCCESS: 'Category deleted successfully',
  GET_CATEGORIES_SUCCESS: 'Get categories successfully',
  GET_CATEGORY_SUCCESS: 'Get category successfully',
  GET_CATEGORY_TREE_SUCCESS: 'Get category tree successfully',
  GET_CATEGORY_BREADCRUMB_SUCCESS: 'Get category breadcrumb successfully',
  GET_CATEGORY_CHILDREN_SUCCESS: 'Get category children successfully',
  TOGGLE_CATEGORY_STATUS_SUCCESS: 'Toggle category status successfully'
} as const

export const PRODUCTS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',

  // Product Messages
  PRODUCT_NOT_FOUND: 'Product not found',
  PRODUCT_ALREADY_EXISTS: 'Product with this name or SKU already exists',
  PRODUCT_SLUG_ALREADY_EXISTS: 'Product slug already exists',
  SKU_ALREADY_EXISTS: 'SKU already exists',
  BARCODE_ALREADY_EXISTS: 'Barcode already exists',
  CATEGORY_NOT_FOUND: 'Category not found',
  BRAND_NOT_FOUND: 'Brand not found',
  INSUFFICIENT_STOCK: 'Số lượng tồn kho không đủ.',
  PRODUCT_DETAIL_NOT_FOUND: 'Product detail not found',
  PRODUCT_MEDIA_NOT_FOUND: 'Product media not found',

  // Validation Messages
  NAME_IS_REQUIRED: 'Product name is required',
  NAME_MUST_BE_STRING: 'Product name must be a string',
  NAME_LENGTH_INVALID: 'Product name must be between 1 and 200 characters',
  SLUG_MUST_BE_STRING: 'Product slug must be a string',
  SLUG_FORMAT_INVALID: 'Product slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Product slug must be between 1 and 200 characters',
  SKU_IS_REQUIRED: 'SKU is required',
  SKU_MUST_BE_STRING: 'SKU must be a string',
  SKU_FORMAT_INVALID: 'SKU must contain only uppercase letters, numbers, and hyphens',
  SKU_LENGTH_INVALID: 'SKU must be between 3 and 50 characters',
  BARCODE_MUST_BE_STRING: 'Barcode must be a string',
  BARCODE_LENGTH_INVALID: 'Barcode must be between 8 and 50 characters',
  SHORT_DESCRIPTION_IS_REQUIRED: 'Short description is required',
  SHORT_DESCRIPTION_MUST_BE_STRING: 'Short description must be a string',
  SHORT_DESCRIPTION_LENGTH_INVALID: 'Short description must be between 10 and 500 characters',
  CATEGORY_ID_IS_REQUIRED: 'Category ID is required',
  CATEGORY_ID_INVALID: 'Category ID must be a valid ObjectId',
  BRAND_ID_INVALID: 'Brand ID must be a valid ObjectId',
  STOCK_QUANTITY_INVALID: 'Stock quantity must be a non-negative number',
  STOCK_QUANTITY_REQUIRED: 'Stock quantity is required',
  MAX_ORDER_QUANTITY_INVALID: 'Max order quantity must be a positive number',
  STATUS_INVALID: 'Status must be active, discontinued, or out_of_stock',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  REQUIRES_PRESCRIPTION_INVALID: 'Requires prescription must be a boolean',
  FEATURED_IMAGE_MUST_BE_STRING: 'Featured image must be a string',
  FEATURED_IMAGE_URL_INVALID: 'Featured image must be a valid URL',
  PRODUCT_ID_INVALID: 'Product ID must be a valid ObjectId',
  PRICE_INVALID: 'Price must be a non-negative number',
  ORIGINAL_PRICE_INVALID: 'Original price must be a non-negative number',
  COST_PRICE_INVALID: 'Cost price must be a non-negative number',

  // Product Detail Validation
  DOSAGE_FORM_IS_REQUIRED: 'Dosage form is required',
  DOSAGE_FORM_INVALID: 'Dosage form must be tablet, capsule, syrup, injection, cream, or drops',
  PACK_SIZE_IS_REQUIRED: 'Pack size is required',
  PACK_SIZE_MUST_BE_STRING: 'Pack size must be a string',
  PACK_SIZE_LENGTH_INVALID: 'Pack size must be between 1 and 100 characters',
  MANUFACTURER_IS_REQUIRED: 'Manufacturer is required',
  MANUFACTURER_MUST_BE_STRING: 'Manufacturer must be a string',
  MANUFACTURER_LENGTH_INVALID: 'Manufacturer must be between 1 and 200 characters',
  DOSAGE_INSTRUCTIONS_IS_REQUIRED: 'Dosage instructions is required',
  DOSAGE_INSTRUCTIONS_MUST_BE_STRING: 'Dosage instructions must be a string',
  DOSAGE_INSTRUCTIONS_LENGTH_INVALID: 'Dosage instructions must be between 10 and 1000 characters',
  STORAGE_INSTRUCTIONS_IS_REQUIRED: 'Storage instructions is required',
  STORAGE_INSTRUCTIONS_MUST_BE_STRING: 'Storage instructions must be a string',
  STORAGE_INSTRUCTIONS_LENGTH_INVALID: 'Storage instructions must be between 10 and 500 characters',
  ACTIVE_INGREDIENTS_MUST_BE_STRING: 'Active ingredients must be a string',
  ACTIVE_INGREDIENTS_LENGTH_INVALID: 'Active ingredients must be up to 500 characters',
  STRENGTH_MUST_BE_STRING: 'Strength must be a string',
  STRENGTH_LENGTH_INVALID: 'Strength must be up to 100 characters',
  INDICATIONS_MUST_BE_STRING: 'Indications must be a string',
  INDICATIONS_LENGTH_INVALID: 'Indications must be up to 1000 characters',

  // Query Validation
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 5000',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be name, createdAt, stockQuantity, sku, or price',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',
  MIN_STOCK_INVALID: 'Min stock must be a non-negative number',
  MAX_STOCK_INVALID: 'Max stock must be a non-negative number',

  // Success Messages
  CREATE_PRODUCT_SUCCESS: 'Product created successfully',
  UPDATE_PRODUCT_SUCCESS: 'Product updated successfully',
  DELETE_PRODUCT_SUCCESS: 'Product deleted successfully',
  GET_PRODUCTS_SUCCESS: 'Get products successfully',
  GET_PRODUCT_SUCCESS: 'Get product successfully',
  TOGGLE_PRODUCT_STATUS_SUCCESS: 'Toggle product status successfully',
  CREATE_PRODUCT_DETAIL_SUCCESS: 'Product detail created successfully',
  UPDATE_PRODUCT_DETAIL_SUCCESS: 'Product detail updated successfully',
  GET_PRODUCT_DETAIL_SUCCESS: 'Get product detail successfully',
  DELETE_PRODUCT_DETAIL_SUCCESS: 'Product detail deleted successfully',
  CREATE_PRODUCT_MEDIA_SUCCESS: 'Product media created successfully',
  UPDATE_PRODUCT_MEDIA_SUCCESS: 'Product media updated successfully',
  GET_PRODUCT_MEDIA_SUCCESS: 'Get product media successfully',
  DELETE_PRODUCT_MEDIA_SUCCESS: 'Product media deleted successfully'
} as const

export const CARTS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',

  // Cart operations
  GET_CART_SUCCESS: 'Get cart successfully',
  ADD_TO_CART_SUCCESS: 'Add to cart successfully',
  UPDATE_CART_ITEM_SUCCESS: 'Update cart item successfully',
  REMOVE_CART_ITEM_SUCCESS: 'Remove cart item successfully',
  CLEAR_CART_SUCCESS: 'Clear cart successfully',
  GET_CHECKOUT_DATA_SUCCESS: 'Get checkout data successfully',

  // Validation messages
  PRODUCT_ID_IS_REQUIRED: 'Product ID is required',
  PRODUCT_ID_INVALID: 'Product ID must be a valid ObjectId',
  QUANTITY_IS_REQUIRED: 'Quantity is required',
  QUANTITY_INVALID: 'Quantity must be a positive number',
  QUANTITY_MUST_BE_BETWEEN_1_AND_10: 'Quantity must be between 1 and 10',
  PRODUCT_NOT_FOUND: 'Product not found',
  INSUFFICIENT_STOCK: 'Số lượng tồn kho không đủ.',
  CART_ITEM_NOT_FOUND: 'Cart item not found',
  INVALID_SESSION_ID: 'Invalid session ID',
  CART_NOT_FOUND: 'Cart not found',
  ITEM_NOT_FOUND_IN_CART: 'Item not found in cart'
} as const

export const BRANDS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  BRAND_NOT_FOUND: 'Brand not found',
  BRAND_ALREADY_EXISTS: 'Brand with this name or slug already exists',
  CANNOT_DELETE_BRAND_WITH_PRODUCTS: 'Cannot delete brand that has products',

  // Validation Messages
  NAME_IS_REQUIRED: 'Brand name is required',
  NAME_MUST_BE_STRING: 'Brand name must be a string',
  NAME_LENGTH_INVALID: 'Brand name must be between 1 and 100 characters',
  SLUG_MUST_BE_STRING: 'Brand slug must be a string',
  SLUG_FORMAT_INVALID: 'Brand slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Brand slug must be between 1 and 100 characters',
  LOGO_MUST_BE_STRING: 'Logo must be a string',
  LOGO_URL_INVALID: 'Logo URL must be a valid URL',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_INVALID: 'Description must be up to 500 characters',
  WEBSITE_MUST_BE_STRING: 'Website must be a string',
  WEBSITE_URL_INVALID: 'Website must be a valid URL',
  COUNTRY_MUST_BE_STRING: 'Country must be a string',
  COUNTRY_LENGTH_INVALID: 'Country must be up to 100 characters',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  BRAND_ID_INVALID: 'Brand ID must be a valid ObjectId',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be name, createdAt, or productCount',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',

  // Success Messages
  CREATE_BRAND_SUCCESS: 'Brand created successfully',
  UPDATE_BRAND_SUCCESS: 'Brand updated successfully',
  DELETE_BRAND_SUCCESS: 'Brand deleted successfully',
  GET_BRANDS_SUCCESS: 'Get brands successfully',
  GET_BRAND_SUCCESS: 'Get brand successfully',
  TOGGLE_BRAND_STATUS_SUCCESS: 'Toggle brand status successfully'
} as const

export const ORDERS_MESSAGES = {
  // Validation Messages
  ORDER_ID_INVALID: 'Mã đơn hàng không hợp lệ.',
  ORDER_ID_REQUIRED: 'Vui lòng cung cấp mã đơn hàng.',
  ORDER_NOT_FOUND: 'Không tìm thấy đơn hàng.',
  CART_EMPTY: 'Giỏ hàng đang trống.',
  PRESCRIPTION_REQUIRED: 'Một số sản phẩm trong giỏ hàng cần đơn thuốc hợp lệ.',
  INVALID_ORDER_STATUS: 'Trạng thái đơn hàng không hợp lệ.',
  INVALID_PAYMENT_STATUS: 'Trạng thái thanh toán không hợp lệ.',
  INVALID_PAYMENT_METHOD: 'Phương thức thanh toán không hợp lệ.',
  ORDER_STATUS_INVALID: 'Trạng thái đơn hàng không hợp lệ.',
  PAYMENT_STATUS_INVALID: 'Trạng thái thanh toán không hợp lệ.',
  PAYMENT_METHOD_INVALID: 'Phương thức thanh toán không hợp lệ.',
  SHIPPING_ADDRESS_INVALID: 'Invalid shipping address',
  SHIPPING_ADDRESS_REQUIRED: 'Shipping address is required',
  FIRST_NAME_REQUIRED: 'First name is required',
  LAST_NAME_REQUIRED: 'Last name is required',
  PHONE_REQUIRED: 'Phone number is required',
  EMAIL_REQUIRED: 'Email is required',
  ADDRESS_REQUIRED: 'Address is required',
  WARD_REQUIRED: 'Ward is required',
  DISTRICT_REQUIRED: 'District is required',
  PROVINCE_REQUIRED: 'Province is required',
  PAYMENT_METHOD_REQUIRED: 'Payment method is required',
  ORDER_STATUS_REQUIRED: 'Order status is required',
  PAYMENT_STATUS_REQUIRED: 'Payment status is required',
  NOTES_MUST_BE_STRING: 'Notes must be a string',
  NOTES_TOO_LONG: 'Notes must be less than 500 characters',
  TRACKING_NUMBER_MUST_BE_STRING: 'Tracking number must be a string',
  TRACKING_NUMBER_TOO_LONG: 'Tracking number must be less than 100 characters',
  ORDER_NUMBER_EXISTS: 'Order number already exists',
  ITEMS_MUST_BE_ARRAY: 'Items must be an array',
  IS_DIRECT_BUY_MUST_BE_BOOLEAN: 'Is direct buy must be a boolean',
  SHIPPING_METHOD_INVALID: 'Invalid shipping method',
  SHIPPING_METHOD_REQUIRED: 'Shipping method is required',

  // Success Messages
  CREATE_ORDER_SUCCESS: 'Tạo đơn hàng thành công.',
  GET_ORDERS_SUCCESS: 'Tải danh sách đơn hàng thành công.',
  GET_ORDER_SUCCESS: 'Tải thông tin đơn hàng thành công.',
  UPDATE_ORDER_STATUS_SUCCESS: 'Cập nhật trạng thái đơn hàng thành công.',
  UPDATE_PAYMENT_STATUS_SUCCESS: 'Cập nhật trạng thái thanh toán thành công.',
  CANCEL_ORDER_SUCCESS: 'Hủy đơn hàng thành công.',

  // Error Messages
  CREATE_ORDER_FAILED: 'Không thể tạo đơn hàng. Vui lòng thử lại.',
  UPDATE_ORDER_FAILED: 'Không thể cập nhật đơn hàng. Vui lòng thử lại.',
  CANCEL_ORDER_FAILED: 'Không thể hủy đơn hàng. Vui lòng thử lại.',
  GET_ORDER_STATS_SUCCESS: 'Tải thống kê đơn hàng thành công.',
  GET_PAYMENT_URL_SUCCESS: 'Get payment URL successfully',
  PAYOS_CREATE_URL_FAILED: 'Failed to create PayOS payment URL',
  MOMO_CREATE_URL_FAILED: 'Failed to create Momo payment URL',
  INVALID_WEBHOOK_DATA: 'Invalid Webhook Data',
  INVALID_SIGNATURE: 'Invalid signature',
  PAYMENT_ORDER_INFO_PREFIX: 'Thanh toan don hang #'
} as const

export const PRESCRIPTIONS_MESSAGES = {
  // Success Messages
  UPLOAD_PRESCRIPTION_SUCCESS: 'Tải đơn thuốc lên thành công.',
  GET_PRESCRIPTIONS_SUCCESS: 'Tải danh sách đơn thuốc thành công.',
  GET_PRESCRIPTION_SUCCESS: 'Tải thông tin đơn thuốc thành công.',
  VERIFY_PRESCRIPTION_SUCCESS: 'Xác nhận đơn thuốc thành công.',
  GET_PENDING_PRESCRIPTIONS_SUCCESS: 'Tải danh sách đơn thuốc chờ xử lý thành công.',

  // Error Messages
  UPLOAD_PRESCRIPTION_FAILED: 'Không thể tải đơn thuốc lên. Vui lòng thử lại.',
  PRESCRIPTION_NOT_FOUND: 'Không tìm thấy đơn thuốc.',
  INVALID_PRESCRIPTION_STATUS: 'Trạng thái đơn thuốc không hợp lệ.',
  PRESCRIPTION_ALREADY_VERIFIED: 'Đơn thuốc đã được xác nhận trước đó.',
  UNAUTHORIZED_TO_VERIFY: 'Bạn không có quyền xác nhận đơn thuốc này.',
  INVALID_MEDICATION_DATA: 'Thông tin thuốc trong đơn chưa hợp lệ.',
  MISSING_DOCTOR_INFO: 'Vui lòng bổ sung thông tin bác sĩ.',
  INVALID_PRESCRIPTION_DATE: 'Ngày kê đơn không hợp lệ.',
  GET_PRESCRIPTION_STATS_SUCCESS: 'Tải thống kê đơn thuốc thành công.',
  ACCESS_DENIED: 'Bạn không có quyền truy cập nội dung này.'
} as const

export const PHARMACIST_MESSAGES = {
  // Dashboard
  GET_DASHBOARD_STATS_SUCCESS: 'Tải thống kê dashboard thành công.',
  GET_RECENT_ACTIVITIES_SUCCESS: 'Tải hoạt động gần đây thành công.',

  // Profile
  GET_PROFILE_SUCCESS: 'Get pharmacist profile successfully',
  UPDATE_PROFILE_SUCCESS: 'Update pharmacist profile successfully',
  UPDATE_SETTINGS_SUCCESS: 'Update pharmacist settings successfully',

  // Patient
  GET_PATIENT_INFO_SUCCESS: 'Get patient information successfully',
  GET_PATIENT_HISTORY_SUCCESS: 'Get patient history successfully',
  PATIENT_NOT_FOUND: 'Patient not found',

  // Medical Info
  GET_MEDICAL_INFO_SUCCESS: 'Get patient medical information successfully',
  UPDATE_MEDICAL_INFO_SUCCESS: 'Update patient medical information successfully',
  ADD_ALLERGY_SUCCESS: 'Add allergy to patient successfully',

  // Patient Notes
  CREATE_NOTE_SUCCESS: 'Create patient note successfully',
  GET_NOTES_SUCCESS: 'Get patient notes successfully',
  UPDATE_NOTE_SUCCESS: 'Update patient note successfully',

  // Medications
  GET_MEDICATIONS_SUCCESS: 'Get patient medications successfully',
  CHECK_INTERACTIONS_SUCCESS: 'Check drug interactions successfully',

  // Order Management
  CREATE_ORDER_SUCCESS: 'Tạo đơn hàng thành công.',
  GET_ORDERS_SUCCESS: 'Tải danh sách đơn hàng thành công.',
  GET_ORDER_DETAILS_SUCCESS: 'Tải chi tiết đơn hàng thành công.',
  UPDATE_ORDER_STATUS_SUCCESS: 'Cập nhật đơn hàng thành công.',
  ORDER_NOT_FOUND: 'Không tìm thấy đơn hàng hoặc bạn không có quyền thao tác đơn hàng này.',
  GET_ORDER_STATS_SUCCESS: 'Tải thống kê đơn hàng thành công.',

  // Settings & Profile
  UPDATE_PASSWORD_SUCCESS: 'Update password successfully',
  GET_WORKING_STATS_SUCCESS: 'Get working statistics successfully',
  UPDATE_ONLINE_STATUS_SUCCESS: 'Update online status successfully',

  // Error Messages
  UNAUTHORIZED_ACCESS: 'Bạn không có quyền truy cập chức năng này.',
  INVALID_PHARMACIST_ID: 'Mã dược sĩ không hợp lệ.',
  PHARMACIST_NOT_FOUND: 'Không tìm thấy thông tin dược sĩ.',
  OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ không chính xác.',
  OLD_PASSWORD_IS_REQUIRED: 'Vui lòng nhập mật khẩu cũ.',
  NEW_PASSWORD_IS_REQUIRED: 'Vui lòng nhập mật khẩu mới.',
  PASSWORD_MUST_BE_STRONG: 'Mật khẩu phải có ít nhất 6 ký tự.',
  LICENSE_REQUIRED: 'Bạn cần cập nhật số chứng chỉ hành nghề trong Cài đặt trước khi sử dụng chức năng dược sĩ.',
  PHARMACIST_NOT_ONLINE: 'Bạn cần bật trạng thái Online để sử dụng chức năng dược sĩ.',
  CHECK_LICENSE_FAILED: 'Không thể kiểm tra thông tin hành nghề. Vui lòng thử lại sau.',
  ONLY_PHARMACIST_ACCESS: 'Chỉ tài khoản dược sĩ mới được sử dụng chức năng này.'
} as const

export const CHATS_MESSAGES = {
  // Validation Messages
  CONVERSATION_ID_REQUIRED: 'Conversation ID is required',
  CONVERSATION_ID_INVALID: 'Conversation ID must be a valid ObjectId',
  PHARMACIST_ID_REQUIRED: 'Pharmacist ID is required',
  PHARMACIST_ID_INVALID: 'Pharmacist ID must be a valid ObjectId',
  CONTENT_REQUIRED: 'Message content is required',
  CONTENT_MUST_BE_STRING: 'Message content must be a string',
  CONTENT_TOO_LONG: 'Message content must be less than 2000 characters',
  MESSAGE_TYPE_INVALID: 'Message type must be text or image',
  IMAGE_URL_MUST_BE_STRING: 'Image URL must be a string',
  IMAGE_URL_INVALID: 'Image URL must be a valid URL',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',

  // Success Messages
  GET_CONVERSATIONS_SUCCESS: 'Get conversations successfully',
  GET_CONVERSATION_SUCCESS: 'Get conversation successfully',
  CREATE_CONVERSATION_SUCCESS: 'Create conversation successfully',
  SEND_MESSAGE_SUCCESS: 'Message sent successfully',
  GET_MESSAGES_SUCCESS: 'Get messages successfully',
  MARK_AS_READ_SUCCESS: 'Messages marked as read successfully',
  GET_PHARMACIST_SUCCESS: 'Get pharmacist information successfully',
  DELETE_CONVERSATION_SUCCESS: 'Delete conversation successfully',

  // Error Messages
  CONVERSATION_NOT_FOUND: 'Conversation not found',
  MESSAGE_NOT_FOUND: 'Message not found',
  UNAUTHORIZED_ACCESS: 'You are not authorized to access this conversation',
  ONLY_CUSTOMERS_CAN_CREATE_CONVERSATION: 'Only customers can create conversations with pharmacists',
  SEND_MESSAGE_FAILED: 'Failed to send message',
  GET_MESSAGES_FAILED: 'Failed to get messages',
  PHARMACIST_NOT_FOUND: 'Pharmacist not found',
  CUSTOMER_NOT_FOUND: 'Customer not found',
  NO_PHARMACIST_AVAILABLE: 'No pharmacist available at the moment'
} as const

export const ADMIN_MESSAGES = {
  GET_DASHBOARD_STATS_SUCCESS: 'Get dashboard statistics successfully',
  GET_RECENT_ACTIVITIES_SUCCESS: 'Get recent activities successfully',
  GET_SYSTEM_HEALTH_SUCCESS: 'Get system health successfully',
  GET_ALL_USERS_SUCCESS: 'Get all users successfully',
  GET_USER_STATS_SUCCESS: 'Get user statistics successfully',
  GET_PHARMACIST_STATS_SUCCESS: 'Get pharmacist statistics successfully',
  CREATE_USER_SUCCESS: 'User created successfully',
  UPDATE_USER_SUCCESS: 'User updated successfully',
  DELETE_USER_SUCCESS: 'User deleted successfully',
  RESET_USER_PASSWORD_SUCCESS: 'User password reset successfully',
  VERIFY_USER_EMAIL_SUCCESS: 'User email verified successfully',
  GET_REPORTS_ANALYTICS_SUCCESS: 'Get reports analytics successfully',
  GET_REVENUE_ANALYTICS_SUCCESS: 'Get revenue analytics successfully',
  GET_PRODUCT_ANALYTICS_SUCCESS: 'Get product analytics successfully',
  GET_CUSTOMER_ANALYTICS_SUCCESS: 'Get customer analytics successfully'
} as const

export const REVIEWS_MESSAGES = {
  // Error Messages
  ORDER_NOT_FOUND_OR_NOT_YOURS: 'Order not found or does not belong to you',
  ORDER_NOT_DELIVERED: 'You can only review products from delivered orders',
  PRODUCT_NOT_IN_ORDER: 'Product not found in this order',
  REVIEW_ALREADY_EXISTS: 'You have already reviewed this product. You can edit your existing review instead.',
  REVIEW_NOT_FOUND: 'Review not found',
  NOT_YOUR_REVIEW: 'You can only edit your own reviews',
  RATING_INVALID: 'Rating must be between 1 and 5',
  TITLE_TOO_LONG: 'Title must not exceed 200 characters',
  COMMENT_TOO_SHORT: 'Comment must be at least 10 characters',
  COMMENT_TOO_LONG: 'Comment must not exceed 2000 characters',
  TOO_MANY_IMAGES: 'Maximum 5 images allowed',
  ALREADY_VOTED_HELPFUL: 'You have already marked this review as helpful',
  CANNOT_VOTE_OWN_REVIEW: 'You cannot vote for your own review',
  REJECTION_REASON_REQUIRED: 'Rejection reason is required',
  RATING_REQUIRED: 'Rating is required',
  TITLE_MUST_BE_STRING: 'Title must be a string',
  COMMENT_REQUIRED: 'Review comment is required',
  COMMENT_MUST_BE_STRING: 'Comment must be a string',
  COMMENT_LENGTH_INVALID: 'Comment must be between 10 and 2000 characters',
  IMAGES_MUST_BE_ARRAY: 'Images must be an array',
  REVIEW_ID_REQUIRED: 'Review ID is required',
  REVIEW_ID_INVALID: 'Invalid review ID format',
  STATUS_REQUIRED: 'Status is required',
  STATUS_INVALID: 'Status must be either approved or rejected',
  NOTES_MUST_BE_STRING: 'Notes must be a string',
  SORT_BY_INVALID: 'Sort by must be one of: newest, oldest, highest, lowest, helpful',
  REJECTED_REVIEW_CANNOT_BE_EDITED: 'Rejected reviews cannot be edited. Please contact support if you believe this is an error.',
  REVIEW_NOT_APPROVED: 'Only approved reviews can receive helpful votes',

  // Success
  CREATE_REVIEW_SUCCESS: 'Review created successfully. It will be visible after moderation.',
  GET_PRODUCT_REVIEWS_SUCCESS: 'Get product reviews successfully',
  GET_PRODUCT_REVIEW_STATS_SUCCESS: 'Get product review stats successfully',
  GET_USER_REVIEWS_SUCCESS: 'Get user reviews successfully',
  UPDATE_REVIEW_SUCCESS: 'Review updated successfully. It will be re-moderated if content changed.',
  DELETE_REVIEW_SUCCESS: 'Review deleted successfully',
  MARK_REVIEW_HELPFUL_SUCCESS: 'Review marked as helpful',
  GET_ADMIN_REVIEWS_SUCCESS: 'Get admin reviews successfully',
  GET_ADMIN_REVIEW_STATS_SUCCESS: 'Get admin review stats successfully',
  MODERATE_REVIEW_SUCCESS: 'Review moderated successfully',
  BULK_MODERATE_SUCCESS: 'Bulk moderate reviews completed successfully'
} as const

export const ARTICLES_MESSAGES = {
  // Validation Messages
  ARTICLE_ID_INVALID: 'Article ID must be a valid ObjectId',
  ARTICLE_NOT_FOUND: 'Article not found',
  TITLE_IS_REQUIRED: 'Article title is required',
  TITLE_MUST_BE_STRING: 'Article title must be a string',
  TITLE_LENGTH_INVALID: 'Article title must be between 1 and 200 characters',
  SLUG_MUST_BE_STRING: 'Article slug must be a string',
  SLUG_FORMAT_INVALID: 'Article slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Article slug must be between 1 and 200 characters',
  SLUG_ALREADY_EXISTS: 'Article with this slug already exists',
  EXCERPT_IS_REQUIRED: 'Article excerpt is required',
  EXCERPT_MUST_BE_STRING: 'Article excerpt must be a string',
  EXCERPT_LENGTH_INVALID: 'Article excerpt must be between 10 and 500 characters',
  CONTENT_IS_REQUIRED: 'Article content is required',
  CONTENT_MUST_BE_STRING: 'Article content must be a string',
  CONTENT_LENGTH_INVALID: 'Article content must be at least 50 characters',
  CATEGORY_ID_IS_REQUIRED: 'Category ID is required',
  CATEGORY_ID_INVALID: 'Category ID must be a valid ObjectId',
  FEATURED_IMAGE_MUST_BE_STRING: 'Featured image must be a string',
  FEATURED_IMAGE_URL_INVALID: 'Featured image must be a valid URL',
  STATUS_INVALID: 'Status must be draft, pending, published, or archived',
  IS_FEATURED_INVALID: 'Is featured must be a boolean',
  IS_PINNED_INVALID: 'Is pinned must be a boolean',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be createdAt, publishedAt, viewCount, or title',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',
  ARTICLE_PERMISSION_DENIED: 'You do not have permission to manage this article',
  ARTICLE_PUBLISH_PERMISSION_DENIED: 'Only admin can publish, archive, feature, or pin articles',

  // Success Messages
  CREATE_ARTICLE_SUCCESS: 'Article created successfully',
  UPDATE_ARTICLE_SUCCESS: 'Article updated successfully',
  DELETE_ARTICLE_SUCCESS: 'Article deleted successfully',
  GET_ARTICLES_SUCCESS: 'Get articles successfully',
  GET_ARTICLE_SUCCESS: 'Get article successfully',
  PUBLISH_ARTICLE_SUCCESS: 'Article published successfully',
  ARCHIVE_ARTICLE_SUCCESS: 'Article archived successfully',
  INCREMENT_VIEW_SUCCESS: 'Article view count updated',
  GET_RELATED_ARTICLES_SUCCESS: 'Get related articles successfully',
  GET_RELATED_PRODUCTS_SUCCESS: 'Get related products successfully',
  TRACK_JOURNEY_EVENT_SUCCESS: 'Article journey event tracked successfully',
  GET_JOURNEY_ANALYTICS_SUCCESS: 'Get article journey analytics successfully',
  GET_ADMIN_INSIGHTS_SUCCESS: 'Get article admin insights successfully',
  ARTICLE_AI_ASSIST_SUCCESS: 'Article AI assistance generated successfully',
  ARTICLE_AI_ASK_SUCCESS: 'Article AI answer generated successfully',
  GET_PERSONALIZED_ARTICLES_SUCCESS: 'Get personalized articles successfully'
} as const

export const HEALTH_CATEGORIES_MESSAGES = {
  // Validation Messages
  CATEGORY_ID_INVALID: 'Health category ID must be a valid ObjectId',
  CATEGORY_NOT_FOUND: 'Health category not found',
  CATEGORY_ALREADY_EXISTS: 'Health category with this name or slug already exists',
  NAME_IS_REQUIRED: 'Category name is required',
  NAME_MUST_BE_STRING: 'Category name must be a string',
  NAME_LENGTH_INVALID: 'Category name must be between 1 and 100 characters',
  SLUG_MUST_BE_STRING: 'Category slug must be a string',
  SLUG_FORMAT_INVALID: 'Category slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Category slug must be between 1 and 100 characters',
  DESCRIPTION_IS_REQUIRED: 'Description is required',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_INVALID: 'Description must be between 1 and 500 characters',
  ORDER_INVALID: 'Order must be a non-negative number',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be name, order, articleCount, or createdAt',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',

  // Success Messages
  CREATE_CATEGORY_SUCCESS: 'Health category created successfully',
  UPDATE_CATEGORY_SUCCESS: 'Health category updated successfully',
  DELETE_CATEGORY_SUCCESS: 'Health category deleted successfully',
  GET_CATEGORIES_SUCCESS: 'Get health categories successfully',
  GET_CATEGORY_SUCCESS: 'Get health category successfully'
} as const

export const RETURN_REQUESTS_MESSAGES = {
  // Validation Messages
  REQUEST_ID_INVALID: 'Return request ID must be a valid ObjectId',
  REQUEST_ID_REQUIRED: 'Return request ID is required',
  ORDER_ID_INVALID: 'Order ID must be a valid ObjectId',
  ORDER_ID_REQUIRED: 'Order ID is required',
  ITEMS_REQUIRED: 'At least one item is required for return',
  ITEMS_MUST_BE_ARRAY: 'Items must be an array',
  REASON_REQUIRED: 'Return reason is required',
  REASON_INVALID: 'Invalid return reason',
  REASON_DETAIL_REQUIRED: 'Reason detail is required',
  REASON_DETAIL_MUST_BE_STRING: 'Reason detail must be a string',
  REASON_DETAIL_LENGTH_INVALID: 'Reason detail must be between 10 and 1000 characters',
  EVIDENCE_MUST_BE_ARRAY: 'Evidence must be an array of URLs',
  EVIDENCE_REQUIRED: 'At least one evidence image/video is required',
  TYPE_INVALID: 'Type must be refund or exchange',
  REFUND_METHOD_INVALID: 'Refund method must be original, bank_transfer, or wallet',
  STATUS_INVALID: 'Invalid return status',
  BANK_NAME_REQUIRED: 'Bank name is required for bank transfer refund',
  ACCOUNT_NUMBER_REQUIRED: 'Account number is required for bank transfer refund',
  ACCOUNT_HOLDER_REQUIRED: 'Account holder name is required for bank transfer refund',
  AMOUNT_INVALID: 'Amount must be a positive number',
    NOTES_MUST_BE_STRING: 'Notes must be a string',
    NOTES_LENGTH_INVALID: 'Notes must be less than 1000 characters',
    TRACKING_NUMBER_MUST_BE_STRING: 'Tracking number must be a string',
    TRACKING_NUMBER_NOT_ALLOWED: 'Return tracking number is generated by the system',
    CONDITION_INVALID: 'Condition must be good, damaged, opened, or unusable',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',

  // Business Logic Errors
  REQUEST_NOT_FOUND: 'Return request not found',
  ORDER_NOT_FOUND: 'Order not found',
  ORDER_NOT_DELIVERED: 'Order must be delivered before requesting return',
  RETURN_PERIOD_EXPIRED: 'Return period has expired (7 days for OTC, 3 days for Rx)',
  PRESCRIPTION_PRODUCT_NOT_RETURNABLE: 'Prescription medicines cannot be returned unless defective or wrong item',
  REQUEST_ALREADY_EXISTS: 'A return request already exists for this order',
  REQUEST_ALREADY_PROCESSED: 'This return request has already been processed',
  REQUEST_CANNOT_BE_CANCELLED: 'This return request cannot be cancelled',
  REQUEST_NOT_EDITABLE: 'This return request can no longer be edited',
  PRODUCT_NOT_IN_ORDER: 'Product not found in the original order',
  QUANTITY_EXCEEDS_ORDERED: 'Số lượng yêu cầu trả vượt quá số lượng còn lại có thể hoàn của đơn hàng',
    INSUFFICIENT_EVIDENCE: 'Insufficient evidence provided for this return reason',
    REFUND_ALREADY_PROCESSED: 'Refund has already been processed for this request',
      AWAITING_RETURN_SHIPMENT: 'Waiting for customer to ship return items',
      RETURN_SHIPMENT_NOT_ARRANGED: 'Return pickup has not been arranged yet',
      RETURN_DEADLINE_PASSED: 'Return shipment deadline has passed',
      TRACKING_PROVIDER_NOT_MOCK: 'Mock tracking updates are only available for mock_carrier return shipments',

  // Success Messages
  CREATE_REQUEST_SUCCESS: 'Return request created successfully',
  GET_REQUESTS_SUCCESS: 'Get return requests successfully',
  GET_REQUEST_SUCCESS: 'Get return request successfully',
  UPDATE_REQUEST_SUCCESS: 'Return request updated successfully',
  CANCEL_REQUEST_SUCCESS: 'Return request cancelled successfully',
    APPROVE_REQUEST_SUCCESS: 'Return request approved successfully',
    REJECT_REQUEST_SUCCESS: 'Return request rejected successfully',
    ARRANGE_RETURN_SUCCESS: 'Return pickup arranged successfully',
    RECEIVE_ITEMS_SUCCESS: 'Return items received and verified',
  PROCESS_REFUND_SUCCESS: 'Refund processed successfully',
    COMPLETE_REQUEST_SUCCESS: 'Return request completed successfully',
    GET_REQUEST_STATS_SUCCESS: 'Get return request statistics successfully',
    GET_RETURN_TRACKING_SUCCESS: 'Get return tracking successfully',
    UPDATE_RETURN_TRACKING_SUCCESS: 'Return tracking updated successfully'
  } as const
