export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH_MUST_BE_FROM_2_TO_100: 'Name must be between 2 and 100 characters long',
  NAME_MUST_BE_STRING: 'Name must be a string',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_OR_PASSWORD_IS_NOT_CORRECT: 'Email or password is not correct',
  INVALID_EMAIL: 'Invalid email format',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  PASSWORD_TOO_WEAK: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Password must be between 6 and 50 characters long',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Confirm password must be between 6 and 50 characters long',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_MUST_BE_STRING: 'Date of birth must be a string',
  DATE_OF_BIRTH_MUST_BE_IN_THE_PAST: 'Date of birth must be in the past',
  DATE_MUST_BE_ISO8601: 'Date must be in ISO 8601 format',
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_FAILED: 'Login failed',
  REGISTER_SUCCESS: 'Registration successful',
  REGISTER_FAILED: 'Registration failed',
  CHECK_EMAIL_FAILED: 'Check email exists failed',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: 'Used refresh token or not exists',
  LOGOUT_SUCCESS: 'Logout successful',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_VERIFY_SUCCESS: 'Email verification successful',
  INVALID_EMAIL_VERIFY_TOKEN: 'Invalid email verify token',
  RESEND_EMAIL_VERIFY_SUCCESS: 'Resend email verification successful',
  EMAIL_NOT_FOUND: 'Email not found',
  FORGOT_PASSWORD_EMAIL_SENT:
    'If that email address is in our database, we will send you an email to reset your password',
  RESET_PASSWORD_TOKEN_IS_REQUIRED: 'Reset password token is required',
  INVALID_RESET_PASSWORD_TOKEN: 'Invalid reset password token',
  RESET_PASSWORD_SUCCESS: 'Reset password successful',
  RESET_PASSWORD_FAILED: 'Reset password failed',
  INVALID_FORGOT_PASSWORD_TOKEN: 'Invalid forgot password token',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Verify forgot password token successful',
  GET_PROFILE_SUCCESS: 'Get profile successful',
  USER_NOT_VERIFIED: 'User not verified. Please verify your email first',
  UPDATE_PROFILE_SUCCESS: 'Update profile successful',
  BIO_LENGTH_MUST_BE_UP_TO_500: 'Bio must be up to 500 characters long',
  BIO_MUST_BE_STRING: 'Bio must be a string',
  LOCATION_LENGTH_MUST_BE_UP_TO_100: 'Location must be up to 100 characters long',
  LOCATION_MUST_BE_STRING: 'Location must be a string',
  WEBSITE_MUST_BE_A_VALID_URL: 'Website must be a valid URL',
  BIO_MUST_BE_AT_MOST_500_CHARACTERS_LONG: 'Bio must be at most 500 characters long',
  LOCATION_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Location must be at most 400 characters long',
  WEBSITE_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Website must be at most 400 characters long',
  USERNAME_MUST_BE_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_FROM_2_TO_30: 'Username must be between 2 and 30 characters long',
  IMAGE_URL_MUST_BE_STRING: 'Image URL must be a string',
  IMAGE_URL_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Image URL must be at most 400 characters long',
  GET_ME_SUCCESS: 'Get me successful',
  FOLLOW_USER_SUCCESS: 'Follow user successful',
  FOLLOW_USER_ID_MUST_BE_STRING: 'follow_user_id must be a string',
  FOLLOW_USER_ID_IS_REQUIRED: 'follow_user_id is required',
  CANNOT_FOLLOW_YOURSELF: 'You cannot follow yourself',
  ALREADY_FOLLOWING_THIS_USER: 'You are already following this user',
  FOLLOW_USER_ID_MUST_BE_A_VALID_ID: 'follow_user_id must be a valid ID',
  ALREADY_FOLLOWED_USER: 'You have already followed this user',
  INVALID_USER_ID: 'Invalid user ID',
  ALREADY_UNFOLLOWED_USER: 'You have already unfollowed this user',
  UNFOLLOW_USER_SUCCESS: 'Unfollow user successful',
  CANNOT_FOLLOW_OR_UNFOLLOW_YOURSELF: 'You cannot follow or unfollow yourself',
  USERNAME_MUST_BE_4_15_CHARACTERS_LONG_AND_CAN_ONLY_CONTAIN_LETTERS_NUMBERS_AND_UNDERSCORES:
    'Username must be 4-15 characters long and can only contain letters, numbers, and underscores',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  CURRENT_PASSWORD_IS_INCORRECT: 'Current password is incorrect',
  CHANGE_PASSWORD_SUCCESS: 'Change password successful',
  CONFIRM_PASSWORD_DO_NOT_MATCH: 'Confirm password do not match',
  GMAIL_NOT_VERIFIED: 'Gmail account is not verified',
  UPLOAD_IMAGE_SUCCESS: 'Image uploaded successfully',
  FILE_IS_NOT_VALID: 'File is not valid',
  FILE_IS_EMPTY: 'File is empty',
  UPLOAD_VIDEO_SUCCESS: 'Video uploaded successfully',
  REQUIRE_RANGE_HEADER: 'Requires Range header',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successful',
  PHONE_NUMBER_MUST_BE_STRING: 'Phone number must be a string',
  PHONE_NUMBER_LENGTH_INVALID: 'Phone number must be between 10 and 15 characters',
  GENDER_INVALID: 'Gender must be 0 or 1',
  ADDRESS_MUST_BE_OBJECT: 'Address must be an object',
  ADDRESS_INVALID: 'Address is invalid',
  WARD_INVALID: 'Ward is invalid',
  CITY_INVALID: 'City is invalid',
  IS_DEFAULT_INVALID: 'Is default must be boolean',
  LISENSE_NUMBER_MUST_BE_STRING: 'License number must be a string',
  LISENSE_NUMBER_LENGTH_INVALID: 'License number must be between 1 and 50 characters'
} as const
