export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH_MUST_BE_FROM_2_TO_100: 'Name must be between 2 and 100 characters long',
  NAME_MUST_BE_STRING: 'Name must be a string',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_OR_PASSWORD_IS_NOT_CORRECT: 'Email or password is not correct',
  INVALID_EMAIL: 'Invalid email format',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  PASSWORD_TOO_WEAK: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Password must be between 6 and 50 characters long',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Confirm password must be between 6 and 50 characters long',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_MUST_BE_STRING: 'Date of birth must be a string',
  DATE_OF_BIRTH_MUST_BE_IN_THE_PAST: 'Date of birth must be in the past',
  DATE_MUST_BE_ISO8601: 'Date must be in ISO 8601 format',
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_FAILED: 'Login failed',
  REGISTER_SUCCESS: 'Registration successful',
  REGISTER_FAILED: 'Registration failed',
  CHECK_EMAIL_FAILED: 'Check email exists failed',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  USED_REFRESH_TOKEN_OR_NOT_EXISTS: 'Used refresh token or not exists',
  LOGOUT_SUCCESS: 'Logout successful',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_VERIFY_SUCCESS: 'Email verification successful',
  INVALID_EMAIL_VERIFY_TOKEN: 'Invalid email verify token',
  RESEND_EMAIL_VERIFY_SUCCESS: 'Resend email verification successful',
  EMAIL_NOT_FOUND: 'Email not found',
  FORGOT_PASSWORD_EMAIL_SENT:
    'If that email address is in our database, we will send you an email to reset your password',
  RESET_PASSWORD_TOKEN_IS_REQUIRED: 'Reset password token is required',
  INVALID_RESET_PASSWORD_TOKEN: 'Invalid reset password token',
  RESET_PASSWORD_SUCCESS: 'Reset password successful',
  RESET_PASSWORD_FAILED: 'Reset password failed',
  INVALID_FORGOT_PASSWORD_TOKEN: 'Invalid forgot password token',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Verify forgot password token successful',
  GET_PROFILE_SUCCESS: 'Get profile successful',
  USER_NOT_VERIFIED: 'User not verified. Please verify your email first',
  UPDATE_PROFILE_SUCCESS: 'Update profile successful',
  BIO_LENGTH_MUST_BE_UP_TO_500: 'Bio must be up to 500 characters long',
  BIO_MUST_BE_STRING: 'Bio must be a string',
  LOCATION_LENGTH_MUST_BE_UP_TO_100: 'Location must be up to 100 characters long',
  LOCATION_MUST_BE_STRING: 'Location must be a string',
  WEBSITE_MUST_BE_A_VALID_URL: 'Website must be a valid URL',
  BIO_MUST_BE_AT_MOST_500_CHARACTERS_LONG: 'Bio must be at most 500 characters long',
  LOCATION_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Location must be at most 400 characters long',
  WEBSITE_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Website must be at most 400 characters long',
  USERNAME_MUST_BE_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_FROM_2_TO_30: 'Username must be between 2 and 30 characters long',
  IMAGE_URL_MUST_BE_STRING: 'Image URL must be a string',
  IMAGE_URL_MUST_BE_AT_MOST_400_CHARACTERS_LONG: 'Image URL must be at most 400 characters long',
  GET_ME_SUCCESS: 'Get me successful',
  FOLLOW_USER_SUCCESS: 'Follow user successful',
  FOLLOW_USER_ID_MUST_BE_STRING: 'follow_user_id must be a string',
  FOLLOW_USER_ID_IS_REQUIRED: 'follow_user_id is required',
  CANNOT_FOLLOW_YOURSELF: 'You cannot follow yourself',
  ALREADY_FOLLOWING_THIS_USER: 'You are already following this user',
  FOLLOW_USER_ID_MUST_BE_A_VALID_ID: 'follow_user_id must be a valid ID',
  ALREADY_FOLLOWED_USER: 'You have already followed this user',
  INVALID_USER_ID: 'Invalid user ID',
  ALREADY_UNFOLLOWED_USER: 'You have already unfollowed this user',
  UNFOLLOW_USER_SUCCESS: 'Unfollow user successful',
  CANNOT_FOLLOW_OR_UNFOLLOW_YOURSELF: 'You cannot follow or unfollow yourself',
  USERNAME_MUST_BE_4_15_CHARACTERS_LONG_AND_CAN_ONLY_CONTAIN_LETTERS_NUMBERS_AND_UNDERSCORES:
    'Username must be 4-15 characters long and can only contain letters, numbers, and underscores',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  CURRENT_PASSWORD_IS_INCORRECT: 'Current password is incorrect',
  CHANGE_PASSWORD_SUCCESS: 'Change password successful',
  CONFIRM_PASSWORD_DO_NOT_MATCH: 'Confirm password do not match',
  GMAIL_NOT_VERIFIED: 'Gmail account is not verified',
  UPLOAD_IMAGE_SUCCESS: 'Image uploaded successfully',
  FILE_IS_NOT_VALID: 'File is not valid',
  FILE_IS_EMPTY: 'File is empty',
  UPLOAD_VIDEO_SUCCESS: 'Video uploaded successfully',
  REQUIRE_RANGE_HEADER: 'Requires Range header',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successful',
  PHONE_NUMBER_MUST_BE_STRING: 'Phone number must be a string',
  PHONE_NUMBER_LENGTH_INVALID: 'Phone number must be between 10 and 15 characters',
  GENDER_INVALID: 'Gender must be 0 or 1',
  ADDRESS_MUST_BE_OBJECT: 'Address must be an object',
  ADDRESS_INVALID: 'Address is invalid',
  WARD_INVALID: 'Ward is invalid',
  CITY_INVALID: 'City is invalid',
  IS_DEFAULT_INVALID: 'Is default must be boolean',
  LISENSE_NUMBER_MUST_BE_STRING: 'License number must be a string',
  LISENSE_NUMBER_LENGTH_INVALID: 'License number must be between 1 and 50 characters'
} as const

export const CATEGORIES_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_ALREADY_EXISTS: 'Category with this name or slug already exists',
  PARENT_CATEGORY_NOT_FOUND: 'Parent category not found',
  CANNOT_DELETE_CATEGORY_WITH_CHILDREN: 'Cannot delete category that has child categories',
  CANNOT_DELETE_CATEGORY_WITH_PRODUCTS: 'Cannot delete category that contains products',
  INVALID_PARENT_CATEGORY: 'Invalid parent category - would create circular reference',
  MAX_LEVEL_EXCEEDED: 'Maximum category level exceeded (max 3 levels)',

  // Field validation messages
  NAME_IS_REQUIRED: 'Category name is required',
  NAME_MUST_BE_STRING: 'Category name must be a string',
  NAME_LENGTH_INVALID: 'Category name must be between 1 and 100 characters',
  SLUG_IS_REQUIRED: 'Category slug is required',
  SLUG_MUST_BE_STRING: 'Category slug must be a string',
  SLUG_FORMAT_INVALID: 'Category slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Category slug must be between 1 and 100 characters',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_INVALID: 'Description must be up to 500 characters',
  PARENT_ID_MUST_BE_VALID_OBJECT_ID: 'Parent ID must be a valid ObjectId',
  CATEGORY_ID_INVALID: 'Category ID must be a valid ObjectId',
  ICON_MUST_BE_STRING: 'Icon must be a string',
  ICON_URL_INVALID: 'Icon URL must be a valid URL',
  THUMBNAIL_IMAGE_MUST_BE_STRING: 'Thumbnail image must be a string',
  THUMBNAIL_URL_INVALID: 'Thumbnail image URL must be a valid URL',
  SORT_ORDER_INVALID: 'Sort order must be a non-negative number',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  LEVEL_INVALID: 'Level must be between 0 and 10',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',

  // Success messages
  CREATE_CATEGORY_SUCCESS: 'Category created successfully',
  UPDATE_CATEGORY_SUCCESS: 'Category updated successfully',
  DELETE_CATEGORY_SUCCESS: 'Category deleted successfully',
  GET_CATEGORIES_SUCCESS: 'Get categories successfully',
  GET_CATEGORY_SUCCESS: 'Get category successfully',
  GET_CATEGORY_TREE_SUCCESS: 'Get category tree successfully',
  GET_CATEGORY_BREADCRUMB_SUCCESS: 'Get category breadcrumb successfully',
  GET_CATEGORY_CHILDREN_SUCCESS: 'Get category children successfully',
  TOGGLE_CATEGORY_STATUS_SUCCESS: 'Toggle category status successfully'
} as const

export const PRODUCTS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',

  // Product Messages
  PRODUCT_NOT_FOUND: 'Product not found',
  PRODUCT_ALREADY_EXISTS: 'Product with this name or SKU already exists',
  SKU_ALREADY_EXISTS: 'SKU already exists',
  BARCODE_ALREADY_EXISTS: 'Barcode already exists',
  CATEGORY_NOT_FOUND: 'Category not found',
  BRAND_NOT_FOUND: 'Brand not found',
  INSUFFICIENT_STOCK: 'Insufficient stock quantity',
  PRODUCT_DETAIL_NOT_FOUND: 'Product detail not found',
  PRODUCT_MEDIA_NOT_FOUND: 'Product media not found',

  // Validation Messages
  NAME_IS_REQUIRED: 'Product name is required',
  NAME_MUST_BE_STRING: 'Product name must be a string',
  NAME_LENGTH_INVALID: 'Product name must be between 1 and 200 characters',
  SLUG_MUST_BE_STRING: 'Product slug must be a string',
  SLUG_FORMAT_INVALID: 'Product slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Product slug must be between 1 and 200 characters',
  SKU_IS_REQUIRED: 'SKU is required',
  SKU_MUST_BE_STRING: 'SKU must be a string',
  SKU_FORMAT_INVALID: 'SKU must contain only uppercase letters, numbers, and hyphens',
  SKU_LENGTH_INVALID: 'SKU must be between 3 and 50 characters',
  BARCODE_MUST_BE_STRING: 'Barcode must be a string',
  BARCODE_LENGTH_INVALID: 'Barcode must be between 8 and 50 characters',
  SHORT_DESCRIPTION_IS_REQUIRED: 'Short description is required',
  SHORT_DESCRIPTION_MUST_BE_STRING: 'Short description must be a string',
  SHORT_DESCRIPTION_LENGTH_INVALID: 'Short description must be between 10 and 500 characters',
  CATEGORY_ID_IS_REQUIRED: 'Category ID is required',
  CATEGORY_ID_INVALID: 'Category ID must be a valid ObjectId',
  BRAND_ID_INVALID: 'Brand ID must be a valid ObjectId',
  STOCK_QUANTITY_INVALID: 'Stock quantity must be a non-negative number',
  STOCK_QUANTITY_REQUIRED: 'Stock quantity is required',
  MAX_ORDER_QUANTITY_INVALID: 'Max order quantity must be a positive number',
  STATUS_INVALID: 'Status must be active, discontinued, or out_of_stock',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  REQUIRES_PRESCRIPTION_INVALID: 'Requires prescription must be a boolean',
  FEATURED_IMAGE_MUST_BE_STRING: 'Featured image must be a string',
  FEATURED_IMAGE_URL_INVALID: 'Featured image must be a valid URL',
  PRODUCT_ID_INVALID: 'Product ID must be a valid ObjectId',

  // Product Detail Validation
  DOSAGE_FORM_IS_REQUIRED: 'Dosage form is required',
  DOSAGE_FORM_INVALID: 'Dosage form must be tablet, capsule, syrup, injection, cream, or drops',
  PACK_SIZE_IS_REQUIRED: 'Pack size is required',
  PACK_SIZE_MUST_BE_STRING: 'Pack size must be a string',
  PACK_SIZE_LENGTH_INVALID: 'Pack size must be between 1 and 100 characters',
  MANUFACTURER_IS_REQUIRED: 'Manufacturer is required',
  MANUFACTURER_MUST_BE_STRING: 'Manufacturer must be a string',
  MANUFACTURER_LENGTH_INVALID: 'Manufacturer must be between 1 and 200 characters',
  DOSAGE_INSTRUCTIONS_IS_REQUIRED: 'Dosage instructions is required',
  DOSAGE_INSTRUCTIONS_MUST_BE_STRING: 'Dosage instructions must be a string',
  DOSAGE_INSTRUCTIONS_LENGTH_INVALID: 'Dosage instructions must be between 10 and 1000 characters',
  STORAGE_INSTRUCTIONS_IS_REQUIRED: 'Storage instructions is required',
  STORAGE_INSTRUCTIONS_MUST_BE_STRING: 'Storage instructions must be a string',
  STORAGE_INSTRUCTIONS_LENGTH_INVALID: 'Storage instructions must be between 10 and 500 characters',
  ACTIVE_INGREDIENTS_MUST_BE_STRING: 'Active ingredients must be a string',
  ACTIVE_INGREDIENTS_LENGTH_INVALID: 'Active ingredients must be up to 500 characters',
  STRENGTH_MUST_BE_STRING: 'Strength must be a string',
  STRENGTH_LENGTH_INVALID: 'Strength must be up to 100 characters',
  INDICATIONS_MUST_BE_STRING: 'Indications must be a string',
  INDICATIONS_LENGTH_INVALID: 'Indications must be up to 1000 characters',

  // Query Validation
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be name, createdAt, stockQuantity, or sku',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',
  MIN_STOCK_INVALID: 'Min stock must be a non-negative number',
  MAX_STOCK_INVALID: 'Max stock must be a non-negative number',

  // Success Messages
  CREATE_PRODUCT_SUCCESS: 'Product created successfully',
  UPDATE_PRODUCT_SUCCESS: 'Product updated successfully',
  DELETE_PRODUCT_SUCCESS: 'Product deleted successfully',
  GET_PRODUCTS_SUCCESS: 'Get products successfully',
  GET_PRODUCT_SUCCESS: 'Get product successfully',
  TOGGLE_PRODUCT_STATUS_SUCCESS: 'Toggle product status successfully',
  CREATE_PRODUCT_DETAIL_SUCCESS: 'Product detail created successfully',
  UPDATE_PRODUCT_DETAIL_SUCCESS: 'Product detail updated successfully',
  GET_PRODUCT_DETAIL_SUCCESS: 'Get product detail successfully',
  DELETE_PRODUCT_DETAIL_SUCCESS: 'Product detail deleted successfully',
  CREATE_PRODUCT_MEDIA_SUCCESS: 'Product media created successfully',
  UPDATE_PRODUCT_MEDIA_SUCCESS: 'Product media updated successfully',
  GET_PRODUCT_MEDIA_SUCCESS: 'Get product media successfully',
  DELETE_PRODUCT_MEDIA_SUCCESS: 'Product media deleted successfully'
} as const

export const CARTS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',

  // Cart operations
  GET_CART_SUCCESS: 'Get cart successfully',
  ADD_TO_CART_SUCCESS: 'Add to cart successfully',
  UPDATE_CART_ITEM_SUCCESS: 'Update cart item successfully',
  REMOVE_CART_ITEM_SUCCESS: 'Remove cart item successfully',
  CLEAR_CART_SUCCESS: 'Clear cart successfully',
  GET_CHECKOUT_DATA_SUCCESS: 'Get checkout data successfully',

  // Validation messages
  PRODUCT_ID_IS_REQUIRED: 'Product ID is required',
  PRODUCT_ID_INVALID: 'Product ID must be a valid ObjectId',
  QUANTITY_IS_REQUIRED: 'Quantity is required',
  QUANTITY_INVALID: 'Quantity must be a positive number',
  QUANTITY_MUST_BE_BETWEEN_1_AND_10: 'Quantity must be between 1 and 10',
  PRODUCT_NOT_FOUND: 'Product not found',
  INSUFFICIENT_STOCK: 'Insufficient stock quantity',
  CART_ITEM_NOT_FOUND: 'Cart item not found',
  INVALID_SESSION_ID: 'Invalid session ID',
  CART_NOT_FOUND: 'Cart not found',
  ITEM_NOT_FOUND_IN_CART: 'Item not found in cart'
} as const

export const BRANDS_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  BRAND_NOT_FOUND: 'Brand not found',
  BRAND_ALREADY_EXISTS: 'Brand with this name or slug already exists',
  CANNOT_DELETE_BRAND_WITH_PRODUCTS: 'Cannot delete brand that has products',

  // Validation Messages
  NAME_IS_REQUIRED: 'Brand name is required',
  NAME_MUST_BE_STRING: 'Brand name must be a string',
  NAME_LENGTH_INVALID: 'Brand name must be between 1 and 100 characters',
  SLUG_MUST_BE_STRING: 'Brand slug must be a string',
  SLUG_FORMAT_INVALID: 'Brand slug must contain only lowercase letters, numbers, and hyphens',
  SLUG_LENGTH_INVALID: 'Brand slug must be between 1 and 100 characters',
  LOGO_MUST_BE_STRING: 'Logo must be a string',
  LOGO_URL_INVALID: 'Logo URL must be a valid URL',
  DESCRIPTION_MUST_BE_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_INVALID: 'Description must be up to 500 characters',
  WEBSITE_MUST_BE_STRING: 'Website must be a string',
  WEBSITE_URL_INVALID: 'Website must be a valid URL',
  COUNTRY_MUST_BE_STRING: 'Country must be a string',
  COUNTRY_LENGTH_INVALID: 'Country must be up to 100 characters',
  IS_ACTIVE_INVALID: 'Is active must be a boolean',
  IS_ACTIVE_REQUIRED: 'Is active is required',
  BRAND_ID_INVALID: 'Brand ID must be a valid ObjectId',
  PAGE_INVALID: 'Page must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer between 1 and 100',
  SEARCH_MUST_BE_STRING: 'Search query must be a string',
  SEARCH_LENGTH_INVALID: 'Search query must be between 1 and 100 characters',
  SORT_BY_INVALID: 'Sort by must be name, createdAt, or productCount',
  SORT_ORDER_INVALID: 'Sort order must be asc or desc',

  // Success Messages
  CREATE_BRAND_SUCCESS: 'Brand created successfully',
  UPDATE_BRAND_SUCCESS: 'Brand updated successfully',
  DELETE_BRAND_SUCCESS: 'Brand deleted successfully',
  GET_BRANDS_SUCCESS: 'Get brands successfully',
  GET_BRAND_SUCCESS: 'Get brand successfully',
  TOGGLE_BRAND_STATUS_SUCCESS: 'Toggle brand status successfully'
} as const
